config/routes.rb
VsetAuction2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :auctions
  resources :auction_items
  resources :bids, only: [:new, :create]
  resources :comments, only: [:destroy]

  root 'static_pages#home'

  match '/signup',    to: 'users#new',		  via: 'get'
  match '/signin',    to: 'sessions#new',	  via: 'get'
  match '/signout',   to: 'sessions#destroy',	  via: 'delete'
  match '/password_reset',   to: 'sessions#password_reset',	  via: 'get'
  match '/forgot_password',   to: 'sessions#forgot_password',	  via: 'post'
  match '/password_change',   to: 'sessions#password_change',	  via: 'get'
  match '/update_password',   to: 'sessions#update_password',	  via: 'post'
  match '/help',      to: 'static_pages#help',	  via: 'get'
  match '/about',     to: 'static_pages#about',	  via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/no-auction',   to: 'static_pages#no_auction', via: 'get'
  match '/category',  to: 'auction_items#category', via: 'get'
  match '/last_10_bids',  to: 'auction_items#last_10_bids', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def help
  end

  def home
    if signed_in?
      if !current_auction.nil?
        redirect_to current_auction
      else
        render 'no_auction'
      end
    end
  end

  def no_auction
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About VSET Auction</h1>
<p class="lead">VSET Auction is a fun way to support our summer missions program. All the money received through VSET Auction will directly help our short-term missionaries this summer. You can be a part of supporting our missionaries and joining together with God in His command to "go and make disciples of all nations" by putting up items for auction and bidding!</p>

<p class="lead">The Auction will end at 11:59:59pm on <span style="font-weight: bold;"><%= (current_auction.end_time - 1.day).to_s %></span></p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p class="lead">Do you have any questions, comments, or suggestions?</p>

<p class="lead">Contact us at vsetauctionmail[at]gmail[dot]com</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>

<p>How to bid:</p>
<ul>
  <li>Must bid at least the minimum amount</li>
  <li>May only increase the bid by at least the minimum increment amount</li>
  <li>Commenting on auction items is only possible if you bid :)</li>
</ul>

<p>If you are experiencing any problems, please visit the <%= link_to 'contact page', contact_path %> and let us know in detail what the problem is!</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1><%= current_auction.name %></h1>
  <h2>Fight the good fight and bid as if to win the prize!</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/no_auction.html.erb
<h1>No Current Auction</h1>