config/routes.rb
VsetAuction2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :auctions
  resources :auction_items
  resources :bids, only: [:new, :create]
  resources :comments, only: [:destroy]

  root 'static_pages#home'

  match '/signup',    to: 'users#new',		  via: 'get'
  match '/signin',    to: 'sessions#new',	  via: 'get'
  match '/signout',   to: 'sessions#destroy',	  via: 'delete'
  match '/password_reset',   to: 'sessions#password_reset',	  via: 'get'
  match '/forgot_password',   to: 'sessions#forgot_password',	  via: 'post'
  match '/password_change',   to: 'sessions#password_change',	  via: 'get'
  match '/update_password',   to: 'sessions#update_password',	  via: 'post'
  match '/help',      to: 'static_pages#help',	  via: 'get'
  match '/about',     to: 'static_pages#about',	  via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/no-auction',   to: 'static_pages#no_auction', via: 'get'
  match '/category',  to: 'auction_items#category', via: 'get'
  match '/last_10_bids',  to: 'auction_items#last_10_bids', via: 'get'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :user
  has_one :auction_stat
  has_many :auction_items
  
  validates :user_id, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :admin_user, only: [:new, :create, :edit, :index, :destroy]

  def new
    @auction = Auction.new
    @auction_stat = AuctionStat.new
  end

  def show
    @auction = current_auction
  end

  def create
    auction_params[:active] = true
    @auction = current_user.auctions.build(auction_params)
    @auction_stat = @auction.build_auction_stat(auction_stat_params)
    if @auction.save && @auction_stat.save
      flash[:success] = "New Auction created!"

      for auction in Auction.all
        if auction.active? && auction.id != @auction.id
          auction.active = false
          auction.save
          break
        end
      end

      set_auction_dirty

      redirect_to @auction
    else
      render 'new'
    end
  end

  def update
    @auction = Auction.find(params[:id])
    if @auction.update_attributes(auction_params)
      # Handle a successful update
      flash[:success] = "Auction updated"
      redirect_to @auction
    else
      render 'edit'
    end
  end

  def index
    @auctions = Auction.paginate(page: params[:page])
  end

  def destroy
    Auction.find(params[:id]).destroy
    flash[:success] = "Auction deleted"
    redirect_to auctions_url
  end

  private

    def auction_params
      params.require(:auction).permit(:name, :description, :start_time,
				:end_time, :banner_image_path, :active)
    end

    def auction_stat_params
      params.require(:auction_stat).permit(:funds_goal)
    end

    # Before filters

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/auctions_helper.rb
module AuctionsHelper

  def calculate_stats
    @auction_items = @auction.auction_items.includes(:bids).where(auction_id: current_auction.id).order('bids.id ASC')

    @total_pledged = 0
    @total_unpledged = 0
    # TODO: fix this later - don't hardcode school totals
    @total_USC = 0
    @total_UCLA = 0
    @total_UCI = 0
    @total_OTHER = 0
    for auction_item in @auction_items
      max_bid = auction_item.max_bid
      if !max_bid.nil?
        @total_pledged += max_bid

        user = auction_item.bids.last.user
        school = user.user_info.school
        case school
        when UserInfo::USC
          @total_USC += max_bid
        when UserInfo::UCLA
          @total_UCLA += max_bid
        when UserInfo::UCI
          @total_UCI += max_bid
        when UserInfo::OTHER
          @total_OTHER += max_bid
        else
          puts "Warning: Attempting to calculate invalid school " + school
        end
      else
        @total_unpledged += auction_item.min_bid
      end
    end
  end

end

app/views/auctions/_auction.html.erb
<li>
  <%= link_to auction.name, auction %>
  <%= link_to "delete", auction, method: :delete,
      data: { confirm: "You sure?" } %>
</li>

app/views/auctions/index.html.erb
<% provide(:title, 'Auctions') %>
<h1>All Auctions</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @auctions %>
</ul>

<%= link_to "Create new auction", new_auction_path, class: "btn btn-large btn-primary" %>

<%= will_paginate %>

app/views/auctions/new.html.erb
<% provide(:title, 'Create Auction') %>
<h1>Create Auction</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@auction) do |f| %>
      <%= render 'shared/auction_error_messages' %>
  
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :start_time %>
      <%= f.date_field :start_time %>

      <%= f.label :end_time %>
      <%= f.date_field :end_time %>

      <%= f.label :banner_image_path %>
      <%= f.text_field :banner_image_path %>

      <br>

      <%= fields_for(@auction_stat) do |a| %>
      
      <%= a.label :funds_goal %>
      <%= a.text_field :funds_goal %>

      <% end %>

      <%= f.submit "Create auction", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/auctions/show.html.erb
<% provide(:title, @auction.name) %>
<div class="center row">
  <%= image_tag 'https://s3-us-west-2.amazonaws.com/vsetauction/auction_items/images/images/auction_2019.jpg' %>
  <h2>Fight the good fight and bid as if to win the prize!</h2>
<%= link_to "Enter auction", auction_items_path, class: "btn btn-large btn-primary" %>
</div>
<br/>
<% cache(cache_key_for_current_auction_stats @auction) do %>
  <% calculate_stats %>
  <div class="center hero-unit">
    <p>Total items posted: <%= @auction_items.count %></p>
    <p>Total amount pledged: $<%= @total_pledged %></p>
    <p>Total with no bids $<%= @total_unpledged %></p>
    <p>Goal: $<%= @auction.auction_stat.funds_goal %></p>
    <p style="color:red;">USC pledged $<%= @total_USC %></p>
    <p style="color:blue;">UCLA pledged $<%= @total_UCLA %></p>
    <p style="color:green;">UCI pledged $<%= @total_UCI %></p>
    <p style="color:black;">OTHER pledged $<%= @total_OTHER %></p>
  </div>
<% end %>