config/routes.rb
VsetAuction2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :auctions
  resources :auction_items
  resources :bids, only: [:new, :create]
  resources :comments, only: [:destroy]

  root 'static_pages#home'

  match '/signup',    to: 'users#new',		  via: 'get'
  match '/signin',    to: 'sessions#new',	  via: 'get'
  match '/signout',   to: 'sessions#destroy',	  via: 'delete'
  match '/password_reset',   to: 'sessions#password_reset',	  via: 'get'
  match '/forgot_password',   to: 'sessions#forgot_password',	  via: 'post'
  match '/password_change',   to: 'sessions#password_change',	  via: 'get'
  match '/update_password',   to: 'sessions#update_password',	  via: 'post'
  match '/help',      to: 'static_pages#help',	  via: 'get'
  match '/about',     to: 'static_pages#about',	  via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/no-auction',   to: 'static_pages#no_auction', via: 'get'
  match '/category',  to: 'auction_items#category', via: 'get'
  match '/last_10_bids',  to: 'auction_items#last_10_bids', via: 'get'

end

app/views/shared/_auction_error_messages.html.erb
<% if @auction.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@auction.errors.count, "error") %>.
    </div>
    <ul>
    <% @auction.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_auction_item_error_messages.html.erb
<% if @auction_item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@auction_item.errors.count, "error") %>.
    </div>
    <ul>
    <% @auction_item.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_bid_error_messages.html.erb
<% if @bid.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@bid.errors.count, "error") %>.
    </div>
    <ul>
    <% @bid.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_category_menu.html.erb
<div>
  <nav>
    <ul class="nav nav-pills nav-stacked span2">  
      <li><%= link_to 'Add Item', new_auction_item_path, class: "btn btn-small"%></li>
      <li><h4><%= link_to 'All', auction_items_path %></h4></li>
      <li><h4><%= link_to 'Books', category_path(id: AuctionItem::BOOK) %></h4></li>
      <li><h4><%= link_to 'Clothing', category_path(id: AuctionItem::CLOTHING) %></h4></li>
      <li><h4><%= link_to 'Food', category_path(id: AuctionItem::FOOD) %></h4></li>
      <li><h4><%= link_to 'Music', category_path(id: AuctionItem::MUSIC) %></h4></li>
      <li><h4><%= link_to 'Services', category_path(id: AuctionItem::SERVICE) %></h4></li>
      <li><h4><%= link_to 'Technology', category_path(id: AuctionItem::TECHNOLOGY) %></h4></li>
      <li><h4><%= link_to 'Other', category_path(id: AuctionItem::OTHER) %></h4></li>
      <!-- <li><h4><%#= link_to 'Last 12 Bids', last_10_bids_path %></h4></li> -->
    </ul>
  </nav>
</div>

app/views/shared/_comments.html.erb
<div class = "row">
  <ol class="comments">
  <% if !@comments.nil? %>
    <% for comment in @comments %>
      <li>
        <span class="user-name-comment"><%= link_to comment.user.name, comment.user %> says:</span>
        <span class="content"><%= comment.content %></span>
        <span class="timestamp">
          Posted <%= time_ago_in_words(comment.created_at) %> ago.
        </span>
        <span class="delete-comment">
          <% if current_user.admin? || current_user == comment.user %>
            <%= link_to "delete comment", comment, method: :delete,
                                  data: { confirm: "You sure?" } %>
          <% end %>
        </span>
      </li>
    <% end %>
  <% end %>
  </ol>
</div>

app/views/shared/_create_bid_form.html.erb
<div class="row"> 
  <div class="span6">     
    <%= form_for(@bid) do |f| %>
      <%= render 'shared/bid_error_messages' %>
 
      <%= f.hidden_field :auction_item_id, value: @auction_item.id %>
 
      <%= f.label :amount %>
      <div class="input-prepend">
        <span class="add-on">$</span>
      <%= f.text_field :amount %>
      </div>

      <%= fields_for(@comment) do |c| %>

      <br/>
      <%= c.label :content, 'Comment:' %>
      <%= c.text_area :content %>

      <% end %>

      <%= f.submit "Submit bid", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>