config/routes.rb
VsetAuction2::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :auctions
  resources :auction_items
  resources :bids, only: [:new, :create]
  resources :comments, only: [:destroy]

  root 'static_pages#home'

  match '/signup',    to: 'users#new',		  via: 'get'
  match '/signin',    to: 'sessions#new',	  via: 'get'
  match '/signout',   to: 'sessions#destroy',	  via: 'delete'
  match '/password_reset',   to: 'sessions#password_reset',	  via: 'get'
  match '/forgot_password',   to: 'sessions#forgot_password',	  via: 'post'
  match '/password_change',   to: 'sessions#password_change',	  via: 'get'
  match '/update_password',   to: 'sessions#update_password',	  via: 'post'
  match '/help',      to: 'static_pages#help',	  via: 'get'
  match '/about',     to: 'static_pages#about',	  via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/no-auction',   to: 'static_pages#no_auction', via: 'get'
  match '/category',  to: 'auction_items#category', via: 'get'
  match '/last_10_bids',  to: 'auction_items#last_10_bids', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div clas="navbar">
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <% if !signed_in? %>
        <%= link_to "vset auction", root_path, id: "logo" %>
      <% else %>
        <%= link_to "vset auction", auction_items_path, id: "logo" %>
      <% end %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "View Items", auction_items_path %></li>
            <% if admin_user? %>
              <li><%= link_to "Auctions", auctions_path %></li>
            <% end %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
	          <li><%= link_to "Sign in", signin_path %></li>
	        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% if current_auction != nil && DateTime.now.to_date >= current_auction.end_time %>
      <h2 style="color: red;">Auction is OVER!</h2>
      <h3 style="color: red;">Please give money to Jack Cao by Sunday, May 5th</h2>
      <h3 style="color: red;">Please fulfill all your items in a timely manner :)</h3>
    <% end %>
    <%= yield %>
    <div id="push"></div>
    <%#= debug(params) if Rails.env.development? %>
  </div>
</body>
    <%= render 'layouts/footer' %>
</html>